.TH SPACEFM-AUTH 1 "July 2026" "SpaceFM" "User Commands"
.SH NAME
spacefm-auth \- helper used by SpaceFM for privileged actions
.SH SYNOPSIS
.B spacefm-auth
.RI [ arguments ]
.SH DESCRIPTION
spacefm-auth is an internal helper script used by SpaceFM when running
configured privileged commands.
.SH SEE ALSO
.BR spacefm (1)
