.TH SPACEFM 1 "July 2026" "SpaceFM" "User Commands"
.SH NAME
spacefm \- multi-panel tabbed file manager
.SH SYNOPSIS
.B spacefm
.RI [ options ]
.RI [ paths ]
.SH DESCRIPTION
SpaceFM is a multi-panel tabbed file manager with desktop integration,
udev-based device management, customizable menus, Bash integration, and
thumbnail support.
.SH OPTIONS
Run
.B spacefm --help
for the list of options supported by this build.
.SH AUTHOR
SpaceFM was written by IgnorantGuru and contributors.
